/* Reviewed Japanese content layer · Physics Visual Lab v4.2.0 */
(() => {
  "use strict";

  const frac = (n, d, cls = "") => `<span class="math-frac${cls ? ` ${cls}` : ""}"><span>${n}</span><span>${d}</span></span>`;

  window.PVL_JA_INTERFACE = [
    ["Physics Visual Lab", "物理可視化ラボ"],
    ["Physics Visual Lab · 01", "物理可視化ラボ · 01"],
    ["Electromagnetism", "電磁気学"],
    ["Experiments", "実験一覧"],
    ["Live simulation", "リアルタイムシミュレーション"],
    ["Paused", "一時停止中"],
    ["A magnetic moment in a constant magnetic field does not simply tip toward the field. Instead, it precesses around the field direction at a fixed angle. Adjust the parameters to see how direction, frequency, and cone angle respond.", "一定磁場中の磁気モーメントは、単純に磁場方向へ倒れるのではなく、一定の角度を保って磁場のまわりを歳差運動します。パラメータを変え、回転方向・周波数・円錐角の応答を確かめてください。"],
    ["Core equations of Larmor precession", "ラーモア歳差運動の基本方程式"],
    ["Interactive Larmor precession laboratory", "ラーモア歳差運動のインタラクティブ実験"],
    ["View controls", "視点操作"],
    ["Perspective", "透視表示"],
    ["View along +B", "+B方向から見る"],
    ["Three-dimensional Larmor precession animation. Drag the canvas to orbit, drag the magnetic-moment arrow to change the initial angle, and use the wheel to zoom.", "ラーモア歳差運動の3次元アニメーションです。背景をドラッグして視点を回転し、磁気モーメントの矢印をドラッグして初期角を変え、ホイールで拡大縮小できます。"],
    ["Drag empty space to orbit", "背景をドラッグして回転"],
    ["Drag μ to change θ₀", "μをドラッグしてθ₀を変更"],
    ["Scroll to zoom", "スクロールで拡大縮小"],
    ["Experiment Controls", "実験操作"],
    ["Magnetic field strength", "磁場の強さ"],
    ["Magnetic field strength B", "磁場の強さ B"],
    ["Gyromagnetic ratio", "磁気回転比"],
    ["Gyromagnetic ratio γ", "磁気回転比 γ"],
    ["Initial angle", "初期角"],
    ["Initial angle θ₀", "初期角 θ₀"],
    ["Magnetic-field direction", "磁場の向き"],
    ["Pause", "一時停止"],
    ["Resume", "再開"],
    ["Pause animation", "アニメーションを一時停止"],
    ["Resume animation", "アニメーションを再開"],
    ["Reset", "リセット"],
    ["Step", "1ステップ"],
    ["Viewing direction", "観測方向"],
    ["No precession: the angular frequency is zero", "歳差運動なし：角周波数は0"],
    ["Precession period", "歳差周期"],
    ["Normalized torque", "規格化トルク"],
    ["The animation uses a teaching time scale chosen for clarity; ω", "アニメーションには観察しやすい学習用時間尺度を用いますが、ω"],
    ["and the period readout retain their true dimensional relationship.", "と周期表示の次元関係は物理量どおりに保たれます。"],
    ["Three Ten-Second Experiments", "10秒で試せる三つの実験"],
    ["Do not memorize the conclusion first. Press a button, predict what will change, then check your prediction against the animation.", "結論を先に暗記せず、ボタンを押す前に変化を予測し、アニメーションで確かめてください。"],
    ["Reverse the sign of γ", "γの符号を反転"],
    ["The cone angle stays fixed while the precession direction reverses instantly.", "円錐角は変わらず、歳差方向だけが直ちに反転します。"],
    ["Double B", "Bを2倍にする"],
    ["doubles, so the physical period is halved.", "は2倍になり、物理的な周期は半分になります。"],
    ["Bring μ close to B", "μをBへ近づける"],
    ["The orbit radius shrinks because the torque is proportional to sin θ.", "トルクがsin θに比例するため、軌道半径は小さくなります。"],
    ["Run experiment ↗", "実験を実行 ↗"],
    ["Why Does It Not Simply Align with the Field?", "なぜ磁場へ直接そろわないのか"],
    ["The key is that the magnetic torque is always perpendicular to the magnetic moment. It changes the moment's direction, not its magnitude; in an ideal uniform static field, the angle between the moment and the field therefore remains constant.", "磁気トルクは常に磁気モーメントに垂直です。そのため大きさではなく向きだけが変化し、理想的な一様静磁場では磁気モーメントと磁場のなす角が一定に保たれます。"],
    ["Three-step derivation of Larmor precession", "ラーモア歳差運動の3段階導出"],
    ["The field exerts a torque", "磁場がトルクを与える"],
    ["Torque changes angular momentum", "トルクが角運動量を変える"],
    ["Use μ = γJ", "μ = γJを用いる"],
    ["Physics Becomes Visible in Motion", "運動によって物理を可視化する"],
    ["Larmor precession is only the beginning. This collection will grow to include dynamic structures from electromagnetism, quantum mechanics, and classical dynamics.", "ラーモア歳差運動は出発点です。今後、電磁気学・量子力学・古典力学の動的構造を順次追加します。"],
    ["Magnetic moment, gyromagnetic ratio, and a constant field", "磁気モーメント、磁気回転比、一様磁場"],
    ["Active experiment", "実験中"],
    ["Bloch Sphere and Spin", "Bloch球とスピン"],
    ["A geometric picture of quantum states on the sphere", "球面上に表す量子状態の幾何学"],
    ["Coming soon", "近日追加"],
    ["Coupled Oscillators and Normal Modes", "結合振動子と固有モード"],
    ["From beats to collective excitation", "うなりから集団励起へ"],
    ["See equations in motion.", "方程式の運動を見よう。"],
    ["stationary", "静止"],
    ["counterclockwise", "反時計回り"],
    ["clockwise", "時計回り"],
    ["Physics Visual Lab home", "物理可視化ラボのホーム"],
    ["Main navigation", "メインナビゲーション"],
    ["Turn equations into", "方程式を"],
    ["motion you can touch", "操作できる運動へ"],
    ["Begin with a complete physical problem, then unfold it into sub-labs you can operate, predict, derive, and build—from quantum measurement to open collision and circuit studios.", "一つの物理問題を全体像から捉え、操作・予測・導出・設計ができるサブラボへ展開します。量子測定から衝突・回路の自由設計までを扱います。"],
    ["Choose a collection, then a sub-lab", "コレクションを選び、サブラボへ"],
    ["The first level establishes the complete problem and method; the second opens a parameter-driven lab, always paired with a guide and derivation.", "第1階層では問題の全体像と方法を整理し、第2階層ではパラメータを操作できる実験へ進みます。各実験にはガイドと導出を用意しています。"],
    ["History, measurement, three sub-labs", "歴史・測定・3つのサブラボ"],
    ["Projectile and inclined-plane dynamics", "斜方投射と斜面力学"],
    ["Begin with one complete physical problem, then move through the sub-labs extracted from it. Every collection includes context, apparatus, core equations, and a guided learning path.", "一つの物理問題を全体から理解し、そこから抽出したサブラボへ進みます。各コレクションには背景、装置、基本方程式、学習経路があります。"],
    ["LEVEL 1 · CHOOSE A COLLECTION", "第1階層 · コレクションを選択"],
    ["COLLECTION → SUB-LAB → GUIDE & DERIVATION", "コレクション → サブラボ → ガイドと導出"],
    ["The Stern–Gerlach Collection", "Stern–Gerlach実験コレクション"],
    ["Move from magnetic-moment precession in a uniform field to spatial splitting in a gradient and then sequential measurement—one systematic route through spin evolution, readout, and preparation.", "一様磁場中の磁気モーメントの歳差運動から、勾配磁場による空間分離、連続測定へ進み、スピンの時間発展・読み出し・状態準備を体系的に理解します。"],
    ["Beam splitting", "基本ビーム分離"],
    ["Sequential measurement", "連続測定"],
    ["3 sub-labs · about 30 min", "3つのサブラボ · 約30分"],
    ["PLANNED", "計画中"],
    ["Two-Level Systems & Quantum Control", "二準位系と量子制御"],
    ["Single-Particle Interference & Path Amplitudes", "単一粒子干渉と経路振幅"],
    ["FUTURE COLLECTION", "今後のコレクション"],
    ["Roadmap", "開発計画"],
    ["The 1922 silver-beam experiment was designed to test space quantization in old quantum theory, yet later became a prototype of modern quantum measurement. This collection separates the historical question from the spin interpretation, then develops magnetic-moment dynamics, gradient forces, projection operators, and sequential measurement.", "1922年の銀原子線実験は旧量子論の空間量子化を検証するために行われ、のちに現代的な量子測定の原型となりました。本コレクションでは歴史的問題とスピンによる解釈を区別し、磁気モーメントの力学、勾配力、射影演算子、連続測定へ進みます。"],
    ["From space quantization to spin measurement", "空間量子化からスピン測定へ"],
    ["The academic significance of Stern–Gerlach is larger than the familiar two-spot image. The same observation bridges old quantum theory and modern quantum mechanics: first a test of directional quantization, later reinterpreted through spin, operators, and state preparation.", "Stern–Gerlach実験の意義は有名な二本のビームだけではありません。同じ観測事実が旧量子論と現代量子力学を結び、方向量子化の検証から、スピン・演算子・状態準備による解釈へ移行しました。"],
    ["Old quantum theory proposes directional quantization", "旧量子論が方向量子化を提案"],
    ["The Frankfurt experiment: no continuous band", "フランクフルト実験：連続帯は現れなかった"],
    ["Electron spin supplies the modern reinterpretation", "電子スピンによる現代的再解釈"],
    ["The analyzer measures and prepares", "分析器は測定すると同時に状態を準備する"],
    ["Why does Sakurai begin here?", "なぜSakuraiはここから始めるのか"],
    ["A two-state system already contains the essential structure of modern quantum mechanics: state space, Hermitian operators, eigenvalues, the Born rule, projective measurement, and noncommutativity. This collection follows that logic instead of reducing the experiment to a simple up/down story.", "二状態系には、状態空間、エルミート演算子、固有値、Born則、射影測定、非可換性という現代量子力学の基本構造がすでに含まれています。本コレクションも単純な上下二分の物語ではなく、この論理に沿って構成しています。"],
    ["Read the Cambridge excerpt ↗", "Cambridge原版抜粋を確認 ↗"],
    ["Four stages of one apparatus", "一つの装置を構成する四段階"],
    ["Silver oven", "銀原子炉"],
    ["Collimator", "コリメータ"],
    ["Field gradient", "磁場勾配"],
    ["Detector", "検出器"],
    ["From energy to measurement probability", "エネルギーから測定確率へ"],
    ["Three sub-labs extracted from the full experiment", "全実験から抽出した三つのサブラボ"],
    ["The recommended order is 01 → 02 → 03, but every module can be opened directly.", "01 → 02 → 03の順が理解しやすいですが、任意のモジュールを直接開くこともできます。"],
    ["Larmor Precession", "ラーモア歳差運動"],
    ["Stern–Gerlach Beam Splitting", "Stern–Gerlach基本ビーム分離"],
    ["Sequential Stern–Gerlach Measurement", "Stern–Gerlach連続測定"],
    ["Stern–Gerlach Laboratory", "Stern–Gerlach実験室"],
    ["Follow a beam of silver atoms from discrete splitting to sequential analyzers, turning spin measurement into a process you can operate, predict, and test.", "銀原子線の離散的分離から連続分析器までを追い、スピン測定を操作・予測・検証できる過程として理解します。"],
    ["Beam-Splitting Controls", "ビーム分離の制御"],
    ["Sequential-Analyzer Controls", "連続分析器の制御"],
    ["Incident spin state", "入射スピン状態"],
    ["Unpolarized", "無偏極"],
    ["Analyzer direction α", "分析器の方向 α"],
    ["Field gradient ∂ₙB", "磁場勾配 ∂ₙB"],
    ["Atomic-beam flux", "原子線フラックス"],
    ["Overlay the classical continuum", "古典的連続分布を重ねる"],
    ["Brightness represents arrival probability", "明るさは到達確率を表す"],
    ["Particle motion uses a teaching time scale", "粒子運動は学習用時間尺度で表示"],
    ["Selecting one branch prepares a new eigenstate.", "一方の枝を選ぶことは、新しい固有状態を準備することです。"],
    ["The gradient sets the separation", "勾配がビーム間隔を決める"],
    ["The axis sets the probabilities", "測定軸が確率を決める"],
    ["Measurement also prepares a state", "測定は状態準備でもある"],
    ["Set initial conditions and system parameters", "初期条件と系のパラメータを設定する"],
    ["Make a qualitative prediction before moving a control", "操作する前に定性的な予測を立てる"],
    ["Read evidence from trajectories, vectors, and curves", "軌跡・ベクトル・曲線から根拠を読み取る"],
    ["Check against live values and the derivation", "リアルタイム値と導出で検証する"],
    ["Close", "閉じる"]
  ];

  window.PVL_JA_THEORY = {
    "larmor-guide": { kicker:"実験01 · ガイド", title:"ラーモア歳差運動：実験ガイド", body:`<p class="theory-intro">一様・静的な磁場 <i>B</i> 中にある磁気モーメント <i>μ</i> の理想運動を調べます。歳差運動の速さを変える量と、円錐の幾何だけを変える量を区別することが目的です。</p><section class="theory-section"><h3>1. モデルと仮定</h3><ul><li>磁場は空間的に一様で時間に依存しません。</li><li><i>μ=γJ</i> とし、γは符号をもつ磁気回転比です。</li><li>緩和・衝突・放射を無視するため、磁気モーメントは自発的に磁場へ整列しません。</li></ul></section><section class="theory-section"><h3>2. 操作量の役割</h3><table class="theory-table"><tr><th>操作量</th><th>観測される変化</th></tr><tr><td>磁場 B</td><td>ω<sub>L</sub>=|γ|B。Bを2倍にすると周期は半分。</td></tr><tr><td>磁気回転比 γ</td><td>|γ|は速さ、符号は回転方向を決める。</td></tr><tr><td>初期角 θ₀</td><td>円錐の開きだけを変え、ω<sub>L</sub>は変えない。</td></tr></table></section><div class="theory-warning">散逸のないモデルでは最低エネルギー状態への緩和は起こりません。</div>` },
    "larmor-derivation": { kicker:"実験01 · 導出", title:"ラーモア歳差運動：完全な導出", body:`<p class="theory-intro">磁気トルクから運動方程式、周波数、保存量を順に導きます。</p><div class="theory-step"><span>01</span><div><h4>磁気トルク</h4><div class="theory-equation">U=−μ·B, &nbsp; τ=μ×B</div></div></div><div class="theory-step"><span>02</span><div><h4>角運動量の時間発展</h4><div class="theory-equation">${frac("dμ","dt")}=γμ×B</div></div></div><div class="theory-step"><span>03</span><div><h4>Bをz方向に取る</h4><div class="theory-equation">${frac("dμ<sub>x</sub>","dt")}=γBμ<sub>y</sub>, &nbsp; ${frac("dμ<sub>y</sub>","dt")}=−γBμ<sub>x</sub></div><p>μ<sub>z</sub>は一定で、横成分は調和運動を行います。</p></div></div><div class="theory-step"><span>04</span><div><h4>周波数と周期</h4><div class="theory-equation amber">ω<sub>L</sub>=|γ|B, &nbsp; T<sub>L</sub>=${frac("2π","|γ|B")}</div></div></div><div class="theory-step"><span>05</span><div><h4>保存量</h4><div class="theory-equation">${frac("d|μ|²","dt")}=0, &nbsp; ${frac("d(μ·B)","dt")}=0</div><p>|μ|、円錐角、磁気エネルギーが保存されます。</p></div></div>` },
    "sg-guide": { kicker:"実験02–03 · ガイド", title:"Stern–Gerlach：実験ガイド", body:`<p class="theory-intro">Stern–Gerlach装置は内部自由度を空間的なビーム分離へ変換します。重要なのは強い磁場そのものではなく、空間勾配です。</p><section class="theory-section"><h3>1. 装置</h3><ol><li>銀原子炉がほぼ無偏極の原子線を作る。</li><li>コリメータが位置と進行方向を絞る。</li><li>不均一磁場が磁気モーメント成分を横力へ変換する。</li><li>検出器が個々の到達事象を蓄積する。</li></ol></section><section class="theory-section"><h3>2. 一様磁場だけでは不十分</h3><div class="theory-equation">F<sub>n</sub>≈μ<sub>n</sub>${frac("∂B","∂n")}</div></section><section class="theory-section"><h3>3. 推奨操作</h3><ol><li>無偏極線では分析軸を回しても二枝が常に1:1であることを確認する。</li><li>+z状態でα=0°と90°を比較する。</li><li>勾配が確率ではなく空間間隔を変えることを確認する。</li><li>z→zとz→x(+)→zを比較する。</li></ol></section>` },
    "sg-derivation": { kicker:"実験02–03 · 導出", title:"Stern–Gerlach：力から確率へ", body:`<p class="theory-intro">磁場勾配がビームを分離し、状態と測定固有状態の重なりが各枝の確率を決めます。</p><div class="theory-step"><span>01</span><div><h4>磁気双極子の力</h4><div class="theory-equation">U=−μ·B, &nbsp; F=∇(μ·B)</div></div></div><div class="theory-step"><span>02</span><div><h4>スピン1/2の固有値</h4><div class="theory-equation">S<sub>α</sub>=${frac("ℏ","2")}σ·n̂<sub>α</sub></div><p>固有値は±ℏ/2の二つだけです。</p></div></div><div class="theory-step"><span>03</span><div><h4>半角確率</h4><div class="theory-equation amber">P(+α)=|⟨+α|+θ⟩|²=cos²(${frac("θ−α","2")})</div><div class="theory-equation">P(−α)=sin²(${frac("θ−α","2")})</div></div></div><div class="theory-step"><span>04</span><div><h4>枝の選択は状態準備</h4><div class="theory-equation">P(+β|+α)=cos²(${frac("β−α","2")})</div><p>中間分析器は既存値を読むだけでなく、その後の状態を準備します。</p></div></div>` }
  };

  const step = (title, equation, text = "") => `<div class="theory-step"><span>◆</span><div><h4>${title}</h4><div class="theory-equation">${equation}</div>${text ? `<p>${text}</p>` : ""}</div></div>`;
  window.PVL_JA_FOUNDATION_DERIVATIONS = {
    projectile:`<p class="theory-intro">水平運動と鉛直運動を独立に解き、同じ時間変数で結合します。</p>${step("運動方程式",`x(t)=v₀cosθ·t, &nbsp; y(t)=h₀+v₀sinθ·t−${frac("1","2")}gt²`)}${step("飛行時間",`T=${frac("v₀sinθ+√(v₀²sin²θ+2gh₀)","g")}`)}${step("射程",`R=v₀cosθ·T`,"h₀=0のときだけ45°対称性が成り立ちます。")}`,
    incline:`<p class="theory-intro">斜面方向と法線方向へ力を分解します。</p>${step("法線力",`N=mg cosθ`)}${step("静止条件",`|F−mg sinθ|≤μₛN`,"静止摩擦は必要な大きさだけ生じ、常にμNではありません。")}${step("滑動時",`ma=F−mg sinθ+f<sub>k</sub>`)}`,
    "collision-studio":`<p class="theory-intro">衝突前後で運動量を保存し、反発係数で相対速度を結びます。</p>${step("運動量保存",`m₁u₁+m₂u₂=m₁v₁+m₂v₂`)}${step("反発係数",`e=${frac("v₂−v₁","u₁−u₂")}`)}${step("エネルギー",`ΔK=−${frac("1","2")}μ(1−e²)(u₁−u₂)²`)}`,
    oscillator:`<p class="theory-intro">線形強制振動の定常解を複素振幅で求めます。</p>${step("運動方程式",`mẍ+bẋ+kx=F₀cosωt`)}${step("振幅",`A(ω)=${frac("F₀","√[(k−mω²)²+(bω)²]")}`)}${step("位相",`tanδ=${frac("bω","k−mω²")}`)}`,
    pendulum:`<p class="theory-intro">小角近似を外すと周期は楕円積分で与えられます。</p>${step("厳密方程式",`θ̈+${frac("g","L")}sinθ=0`)}${step("小角周期",`T₀=2π√${frac("L","g")}`)}${step("有限振幅補正",`T≈T₀(1+${frac("θ₀²","16")}+${frac("11θ₀⁴","3072")})`)}`,
    "standing-wave":`<p class="theory-intro">固定端境界条件が連続な周波数を離散的な固有モードへ選別します。</p>${step("波速",`v=√${frac("F","μ")}`)}${step("許容波長",`λₙ=${frac("2L","n")}`)}${step("固有周波数",`fₙ=${frac("n","2L")}√${frac("F","μ")}`)}`,
    "rc-circuit":`<p class="theory-intro">Kirchhoffの電圧則と ${frac("dq","dt")} の関係から指数応答が得られます。</p>${step("充電方程式",`${frac("dq","dt")}+${frac("q","RC")}=${frac("V₀","R")}`)}${step("充電",`V<sub>C</sub>=V₀(1−e<sup>−t(RC)⁻¹</sup>)`)}${step("放電",`V<sub>C</sub>=V₀e<sup>−t(RC)⁻¹</sup>`)}`,
    "circuit-studio":`<p class="theory-intro">各枝を直列合成し、共通ノード電圧と電流保存で並列結合します。</p>${step("直列枝",`R<sub>b</sub>=ΣRᵢ`)}${step("並列合成",`${frac("1","R<sub>eq</sub>")}=Σ${frac("1","R<sub>b</sub>")}`)}${step("ノード則",`I<sub>total</sub>=ΣI<sub>b</sub>`)}`,
    induction:`<p class="theory-intro">磁束の時間変化が回路に沿う起電力を生みます。</p>${step("磁束",`NΦ=NBAcosωt`)}${step("Faraday–Lenz則",`ε=−${frac("d(NΦ)","dt")}=NBAωsinωt`)}${step("抵抗負荷",`I(t)=${frac("ε(t)","R")}`)}`,
    "thin-lens":`<p class="theory-intro">近軸近似では屈折を一つの薄い平面へ集約できます。</p>${step("薄レンズ式",`${frac("1","f")}=${frac("1","u")}+${frac("1","v")}`)}${step("倍率",`m=−${frac("v","u")}`)}${step("像距離",`v=${frac("fu","u−f")}`)}`,
    "double-slit":`<p class="theory-intro">有限幅スリットの回折包絡と、二つの中心の干渉因子を振幅レベルで組み合わせます。</p>${step("干渉位相",`α=${frac("πd sinθ","λ")}`)}${step("回折位相",`β=${frac("πa sinθ","λ")}`)}${step("強度",`I=I₀(${frac("sinβ","β")})²cos²α`)}`,
    polarization:`<p class="theory-intro">偏光板は電場振幅を透過軸へ射影し、検出器はその二乗を読み取ります。</p>${step("一枚目",`I₁=I₀cos²(α−θ₀)`)}${step("二枚目",`I₂=I₁cos²(β−α)`)}${step("直交偏光板の間に45°を挿入",`I₂=${frac("I₀","4")}`)}`
  };
  Object.assign(window.PVL_JA_FOUNDATION_DERIVATIONS, {
    "wheatstone-bridge":`<p class="theory-intro">Wheatstoneブリッジは二つの分圧点を零位比較し、未知抵抗を比として求めます。</p>${step("分圧",`Vᴸ=Vₛ${frac("R₂","R₁+R₂")}, &nbsp; Vᴿ=Vₛ${frac("Rₓ","R₃+Rₓ")}`)}${step("零位条件",`Vg=Vᴸ−Vᴿ=0`)}${step("未知抵抗",`Rₓ=${frac("R₂R₃","R₁")}`,"平衡式では電源電圧と検流計抵抗が消去されます。")}`,
    "rlc-resonance":`<p class="theory-intro">直列RLCの正弦定常応答を複素インピーダンスで表します。</p>${step("インピーダンス",`Z=R+j(ωL−${frac("1","ωC")})`)}${step("共振",`f₀=${frac("1","2π√(LC)")}`)}${step("品質係数",`Q=${frac("ω₀L","R")}`,"共振では誘導性と容量性リアクタンスが相殺されます。")}`,
    "optical-bench":`<p class="theory-intro">第一レンズの像を第二レンズの物体として、符号付き距離で逐次計算します。</p>${step("第一段",`${frac("1","f₁")}=${frac("1","u₁")}+${frac("1","v₁")}`)}${step("段間変換",`u₂=d−v₁`)}${step("第二段と総倍率",`${frac("1","f₂")}=${frac("1","u₂")}+${frac("1","v₂")}, &nbsp; M=m₁m₂`)}`,
    "diffraction-grating":`<p class="theory-intro">多数の等間隔溝の干渉が狭い主極大と高い分光能力を生みます。</p>${step("格子方程式",`d sinθₘ=mλ`)}${step("最大次数",`m<sub>max</sub>=⌊${frac("d","λ")}⌋`)}${step("分解能",`R=${frac("λ","Δλ")}=mN`)}`
  });
  window.PVL_JA_FOUNDATION_DERIVATIONS["circuit-studio"]=`<p class="theory-intro">このワークベンチは直並列回路だけに限定せず、任意の名前付きノードへ素子端子を接続し、修正節点解析（MNA）で回路方程式を構成します。</p>${step("基準節点と未知量",`Σi<sub>out</sub>(v)=0`,`0/GNDを基準に選び、非基準節点電圧vを未知量とします。理想電圧源やインダクタには枝電流i<sub>v</sub>を追加します。`)}${step("MNA行列",`[ G&nbsp; B ; C&nbsp; D ][ v ; i<sub>v</sub> ]=[ j ; e ]`,`Gは節点アドミタンス、BとCは電圧定義枝の接続、Dは枝間拘束を表します。`)}${step("素子の構成式",`i<sub>R</sub>=${frac("v<sub>a</sub>−v<sub>b</sub>","R")}, &nbsp; i<sub>C</sub>=C${frac("d(v<sub>a</sub>−v<sub>b</sub>)","dt")}`)}${step("周波数領域と時間離散",`Y<sub>C</sub>=jωC, &nbsp; Y<sub>L</sub>=${frac("1","jωL")}`,`過渡解析では後退オイラー法により、CとLを各時刻の等価コンパニオン回路へ変換します。`)}${step("非線形反復",`J(v<sup>n</sup>)Δv=−F(v<sup>n</sup>), &nbsp; v<sup>n+1</sup>=v<sup>n</sup>+Δv`,`ダイオード、BJT、MOSFETはNewton反復で線形化します。本ツールは教育用の簡潔なモデルであり、実部品の限界設計にはメーカーのSPICEモデルが必要です。`)}`;
})();
